// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.3
// source: common/protocol/addition_id.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdditionIdPolicy int32

const (
	AdditionIdPolicy_HEAD_PREFIX AdditionIdPolicy = 0
	AdditionIdPolicy_BODY_PREFIX AdditionIdPolicy = 1
)

// Enum value maps for AdditionIdPolicy.
var (
	AdditionIdPolicy_name = map[int32]string{
		0: "HEAD_PREFIX",
		1: "BODY_PREFIX",
	}
	AdditionIdPolicy_value = map[string]int32{
		"HEAD_PREFIX": 0,
		"BODY_PREFIX": 1,
	}
)

func (x AdditionIdPolicy) Enum() *AdditionIdPolicy {
	p := new(AdditionIdPolicy)
	*p = x
	return p
}

func (x AdditionIdPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdditionIdPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_common_protocol_addition_id_proto_enumTypes[0].Descriptor()
}

func (AdditionIdPolicy) Type() protoreflect.EnumType {
	return &file_common_protocol_addition_id_proto_enumTypes[0]
}

func (x AdditionIdPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdditionIdPolicy.Descriptor instead.
func (AdditionIdPolicy) EnumDescriptor() ([]byte, []int) {
	return file_common_protocol_addition_id_proto_rawDescGZIP(), []int{0}
}

var File_common_protocol_addition_id_proto protoreflect.FileDescriptor

var file_common_protocol_addition_id_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x78, 0x72, 0x61, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2a, 0x34, 0x0a, 0x10, 0x41, 0x64, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x0f, 0x0a,
	0x0b, 0x48, 0x45, 0x41, 0x44, 0x5f, 0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x42, 0x4f, 0x44, 0x59, 0x5f, 0x50, 0x52, 0x45, 0x46, 0x49, 0x58, 0x10, 0x01, 0x42,
	0x5e, 0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x78, 0x72, 0x61, 0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x50, 0x01, 0x5a, 0x29, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x74, 0x6c, 0x73, 0x2f, 0x78,
	0x72, 0x61, 0x79, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0xaa, 0x02, 0x14, 0x58, 0x72, 0x61, 0x79, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_protocol_addition_id_proto_rawDescOnce sync.Once
	file_common_protocol_addition_id_proto_rawDescData = file_common_protocol_addition_id_proto_rawDesc
)

func file_common_protocol_addition_id_proto_rawDescGZIP() []byte {
	file_common_protocol_addition_id_proto_rawDescOnce.Do(func() {
		file_common_protocol_addition_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_protocol_addition_id_proto_rawDescData)
	})
	return file_common_protocol_addition_id_proto_rawDescData
}

var file_common_protocol_addition_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_protocol_addition_id_proto_goTypes = []any{
	(AdditionIdPolicy)(0), // 0: xray.common.protocol.AdditionIdPolicy
}
var file_common_protocol_addition_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_protocol_addition_id_proto_init() }
func file_common_protocol_addition_id_proto_init() {
	if File_common_protocol_addition_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_protocol_addition_id_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_protocol_addition_id_proto_goTypes,
		DependencyIndexes: file_common_protocol_addition_id_proto_depIdxs,
		EnumInfos:         file_common_protocol_addition_id_proto_enumTypes,
	}.Build()
	File_common_protocol_addition_id_proto = out.File
	file_common_protocol_addition_id_proto_rawDesc = nil
	file_common_protocol_addition_id_proto_goTypes = nil
	file_common_protocol_addition_id_proto_depIdxs = nil
}
