// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common/protocol/addition_id.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdditionIdPolicy int32

const (
	AdditionIdPolicy_HEAD_PREFIX AdditionIdPolicy = 0
	AdditionIdPolicy_BODY_PREFIX AdditionIdPolicy = 1
)

// Enum value maps for AdditionIdPolicy.
var (
	AdditionIdPolicy_name = map[int32]string{
		0: "HEAD_PREFIX",
		1: "BODY_PREFIX",
	}
	AdditionIdPolicy_value = map[string]int32{
		"HEAD_PREFIX": 0,
		"BODY_PREFIX": 1,
	}
)

func (x AdditionIdPolicy) Enum() *AdditionIdPolicy {
	p := new(AdditionIdPolicy)
	*p = x
	return p
}

func (x AdditionIdPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdditionIdPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_common_protocol_addition_id_proto_enumTypes[0].Descriptor()
}

func (AdditionIdPolicy) Type() protoreflect.EnumType {
	return &file_common_protocol_addition_id_proto_enumTypes[0]
}

func (x AdditionIdPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdditionIdPolicy.Descriptor instead.
func (AdditionIdPolicy) EnumDescriptor() ([]byte, []int) {
	return file_common_protocol_addition_id_proto_rawDescGZIP(), []int{0}
}

var File_common_protocol_addition_id_proto protoreflect.FileDescriptor

const file_common_protocol_addition_id_proto_rawDesc = "" +
	"\n" +
	"!common/protocol/addition_id.proto\x12\x14xray.common.protocol*4\n" +
	"\x10AdditionIdPolicy\x12\x0f\n" +
	"\vHEAD_PREFIX\x10\x00\x12\x0f\n" +
	"\vBODY_PREFIX\x10\x01B^\n" +
	"\x18com.xray.common.protocolP\x01Z)github.com/xtls/xray-core/common/protocol\xaa\x02\x14Xray.Common.Protocolb\x06proto3"

var (
	file_common_protocol_addition_id_proto_rawDescOnce sync.Once
	file_common_protocol_addition_id_proto_rawDescData []byte
)

func file_common_protocol_addition_id_proto_rawDescGZIP() []byte {
	file_common_protocol_addition_id_proto_rawDescOnce.Do(func() {
		file_common_protocol_addition_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_protocol_addition_id_proto_rawDesc), len(file_common_protocol_addition_id_proto_rawDesc)))
	})
	return file_common_protocol_addition_id_proto_rawDescData
}

var file_common_protocol_addition_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_protocol_addition_id_proto_goTypes = []any{
	(AdditionIdPolicy)(0), // 0: xray.common.protocol.AdditionIdPolicy
}
var file_common_protocol_addition_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_protocol_addition_id_proto_init() }
func file_common_protocol_addition_id_proto_init() {
	if File_common_protocol_addition_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_protocol_addition_id_proto_rawDesc), len(file_common_protocol_addition_id_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_protocol_addition_id_proto_goTypes,
		DependencyIndexes: file_common_protocol_addition_id_proto_depIdxs,
		EnumInfos:         file_common_protocol_addition_id_proto_enumTypes,
	}.Build()
	File_common_protocol_addition_id_proto = out.File
	file_common_protocol_addition_id_proto_goTypes = nil
	file_common_protocol_addition_id_proto_depIdxs = nil
}
